version: '3'

services:
  app:
    build: ./
    ports:
      - "9000:9000"
    container_name: app
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    container_name: grafana