server:
  port: 9001
spring:
  application:
    name: base-service
  datasource:
    url: jdbc:h2:~/cb-rate-db
    username: sa
    password: 
    driverClassName: org.h2.Driver
    configuration:
      maximum-pool-size: 30
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
  mvc:
    async:
      request-timeout: 30000


# LOGGING
logging:
  config: file:config/log4j2.yml
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG

# TRACE
management:
  endpoints:
    web:
      exposure:
        include: httptrace, prometheus
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
    tags:
      application: ${spring.application.name}
  trace:
    http:
      include: RESPONSE_HEADERS
    # server:
    #   port: 9001

# SQL statements and parameters